### PR TITLE
ci: changed all uses of local branches to main

### PR DESCRIPTION
**Pull request by BenedictHomuth**
## Description

With this PR all workflows / actions now run the CI files from the main branch. This seems to be the best practice to keep all CI activities in sync with main. It also ensures that the main branch is stable, since the checks are run against the main version – meaning that if those pass, main should not be crashed when merging PR branches.

This usage of CI running against main is already present in the steps of  `package`,  `deploy-to-dev-cluster`, `deploy-docs` etc.

## Changelog

- changed `ci.yml`

### CODE REVIEW

**Comment by brandstetterm** [comment]
What happens if they're changed in a PR? We wouldn't know if they work since GitHub will be using the actions from the main branch, right?

**Comment by BenedictHomuth** [comment]
> What happens if they're changed in a PR? We wouldn't know if they work since GitHub will be using the actions from the main branch, right?

By default, yes.
The idea here is to purposefully change the reference from `main` to `dev_branch` when modifying the CI.
Then, you can check if your CI changes work as expected in your `dev_branch`. 

Before merging into main the reference must be reset.

**Comment by brandstetterm** [comment]
> > What happens if they're changed in a PR? We wouldn't know if they work since GitHub will be using the actions from the main branch, right?
> 
> By default, yes. The idea here is to purposefully change the reference from `main` to `dev_branch` when modifying the CI. Then, you can check if your CI changes work as expected in your `dev_branch`.
> 
> Before merging into main the reference must be reset.

But isn't that prone to errors?

**Comment by BenedictHomuth** [comment]
> > > What happens if they're changed in a PR? We wouldn't know if they work since GitHub will be using the actions from the main branch, right?
> > 
> > 
> > By default, yes. The idea here is to purposefully change the reference from `main` to `dev_branch` when modifying the CI. Then, you can check if your CI changes work as expected in your `dev_branch`.
> > Before merging into main the reference must be reset.
> 
> But isn't that prone to errors?

Could be.

Nonetheless, we should standardize our methodology. Either by always testing against `main` or always using the `local` branch. Not a mix of both.

We can talk in the daily about that and accept a final conclusion.

**Comment by BenedictHomuth** [comment]
> > > > What happens if they're changed in a PR? We wouldn't know if they work since GitHub will be using the actions from the main branch, right?
> > > 
> > > 
> > > By default, yes. The idea here is to purposefully change the reference from `main` to `dev_branch` when modifying the CI. Then, you can check if your CI changes work as expected in your `dev_branch`.
> > > Before merging into main the reference must be reset.
> > 
> > 
> > But isn't that prone to errors?
> 
> Could be.
> 
> Nonetheless, we should standardize our methodology. Either by always testing against `main` or always using the `local` branch. Not a mix of both.
> 
> We can talk in the daily about that and accept a final conclusion.

Talked it through in our daily. For now, we concluded to use the `local` version. Therefore the PR is updated.

**Review by brandstetterm — APPROVED** [review]

**Pull request merged**
