### PR TITLE
CI: Docker: Change context path for docker compose

### PR DESCRIPTION
**Pull request by the-homeless-god**
## Description

During the description that says us to navigate to:

```
git clone https://github.com/inovex/scrumlr.io
cd scrumlr.io/deployment/
```

We are finding that current directory will include `docker` dir, that incorrectly will not be found at `docker-compose.yml`

So it would be great to have correct path for one more level at the top

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] The light- and dark-theme are both supported and tested
- [x] The design was implemented and is responsive for all devices and screen sizes
- [x] The application was tested in the most commonly used browsers (e.g. Chrome, Firefox, Safari)

### CODE REVIEW

**Comment by Schwehn42** [comment]
@Lennart01 @mateo-ivc what do you think of this?

**Comment by mateo-ivc** [comment]
> @Lennart01 @mateo-ivc what do you think of this?

This has already been resolved with [#4401](https://github.com/inovex/scrumlr.io/pull/4401/) but we can take over the changes for the docs

**Comment by Schwehn42** [comment]
You're right. I'll resolve the conflicts and merge it then ✌️

**Comment by Schwehn42** [comment]
@mateo-ivc actually I just realized we had yet another update to the docker compose in https://github.com/inovex/scrumlr.io/pull/4521, are the changes here still relevant then?

**Comment by mateo-ivc** [comment]
> @mateo-ivc actually I just realized we had yet another update to the docker compose in #4521, are the changes here still relevant then?
Not really, we could take the change in the docs, but since we need to make changes to the docs anyway, we could add it there.

**Review by Schwehn42 — APPROVED** [review]
Hi @the-homeless-god, since we had some other changes to the docker compose process, most of this is obsolete by now (see https://github.com/inovex/scrumlr.io/pull/4401/ and https://github.com/inovex/scrumlr.io/pull/4521). Hopefully it's easier to use now though, otherwise feel free to create a GitHub discussion. 

The updated docs is still right, so I will approve and merge this.
Thanks for the contribution!

**Pull request merged**
