### PR TITLE
feature: add letter limit to settings input

### LINKED ISSUE #3100: Show indicator for number of letters in settings
The length of the usernames is limited to a maximum of 64 characters. We should show an indicator for how many characters are typed in out of the maximum. Also, we should limit the input field to take no more than 64 characters.

For example:
**Manuel Bran**.............  **11/64**

### PR DESCRIPTION
**Pull request by blxckOxymoron**
## Description

add an indicator to show the maximum and current length of an input field
- Closes #3100 

## Changelog

- added a small text on the top right that shows up when `maxLength` is set and the input is focused
- added a `maxLength` of `64` to the username input
- added a `maxLength` of `128` to the board name input
- updated test snapshot

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] The light- and dark-theme are both supported and tested
- [x] The design was implemented and is responsive for all devices and screen sizes
- [x] The application was tested in the most commonly used browsers (e.g. Chrome, Firefox, Safari)

## (Optional) Visual Changes

grafik

### CODE REVIEW

**Comment by brandstetterm** [comment]
Hey @blxckOxymoron, thank you very much for your contribution!
We would prefer it if the character counter is visible all the time. Could you please change that? 😊

**Comment by blxckOxymoron** [comment]
Okay I will change that and upload a new screenshot. 👍
I originally implemented it like this, but thought that it looked odd when only a few characters are inputed

**Comment by blxckOxymoron** [comment]
okay, it's actually not as bad as I remembered it. 
I still kept it hidden when the input isn't focused but I'm open to changing this as well.

grafik

**Review by brandstetterm — APPROVED** [review]
LGTM 🥳 Thank you!

**Pull request merged**
