### PR TITLE
feat: documentation using github pages

### PR DESCRIPTION
**Pull request by Lennart01**
## Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] The light- and dark-theme are both supported and tested
- [x] The design was implemented and is responsive for all devices and screen sizes
- [x] The application was tested in the most commonly used browsers (e.g. Chrome, Firefox, Safari)

### CODE REVIEW

**Comment by brandstetterm** [comment]
Tbh I would prefer this to be in a separate GitHub repository  :D

**Comment by Schwehn42** [comment]
> Tbh I would prefer this to be in a separate GitHub repository :D

why?

**Comment by Schwehn42** [comment]
I prefer it in here, if it's in another repo I can already see information not being up to date because it was forgotten. The main repository is the most accessible not only for us devs, but also the first place to look for anyone who actually needs them. Furthermore once this is integrated I'm assuming the information won't change that frequently so I don't believe it's going to get in our way.

**Comment by brandstetterm** [comment]
> > Tbh I would prefer this to be in a separate GitHub repository :D
> 
> why?

Because the codebase & commit history of the main application should be kept clean in my opinion. For the same reason, the landing page is a separate project.

**Comment by Schwehn42** [comment]
> Also, as far as I've seen, the GitHub action to deploy the documentation to GitHub pages is planned to run on every commit on main. With 99% of all commits probably not being related to the documentation, that's unnecessary.

Since a commit to main equals a merged PR, I think it would be interesting to know if the whole documentation changes even though something completely unrelated was commited or only the relevant parts are affected. Because in the first case, I completely agree with as this would clutter the history, but if it's a smart tool I think it would be nice to have the most up to date documentation within the same repo.

**Comment by Schwehn42** [comment]
That being said I don't insist on this, so if you really say this is better for the reasons described then I don't mind as well

**Comment by Lennart01** [comment]
> > > Tbh I would prefer this to be in a separate GitHub repository :D
> > 
> > 
> > why?
> 
> Because the codebase & commit history of the main application should be kept clean in my opinion. For the same reason, the landing page is a separate project.
> 
> Also, as far as I've seen, the GitHub action to deploy the documentation to GitHub pages is planned to run on every commit on main. With 99% of all commits probably not being related to the documentation, that's unnecessary.

Which is something we can tackle.
We can only run the docs pipeline if we made changes to the folder like (this)[https://www.cbui.dev/how-to-only-run-github-actions-steps-if-files-change/#:~:text=If%20you%20want%20to%20conditionally,only%20operates%20on%20entire%20workflows.]

**Review by Schwehn42 — APPROVED** [review]

**Pull request merged**
