### PR TITLE
fix: note author list overlap order

### LINKED ISSUE #3039: NoteAuthorList: change avatar overlap order
for 2+ users, the user avatars aren't layered correctly on each other.  
AC: first author should be on the very top, the rest following caterpillar style. (+n) would be last and layered the most bottom.

### PR DESCRIPTION
**Pull request by Schwehn42**
## Description

Resolves #3039
changes the way multiple authors overlap, so that the first author is displayed on the very top, and the rest below "like a caterpillar".

## Changelog
- change z-index of author figures / rest bubble
- some css improvements, e.g. removing obsolete lines

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] The light- and dark-theme are both supported and tested
- [x] The design was implemented and is responsive for all devices and screen sizes
- [x] The application was tested in the most commonly used browsers (e.g. Chrome, Firefox, Safari)

## (Optional) Visual Changes

Bildschirm­foto 2023-06-05 um 16 12 48
Bildschirm­foto 2023-06-05 um 16 13 19

### CODE REVIEW

**Comment by brandstetterm** [comment]
Could you please change the border color to fit the background color of the notes?
image

**Comment by Schwehn42** [comment]
> Could you please change the border color to fit the background color of the notes?

@brandstetterm The colours should now match.  
Note that the circle is now also visible when the note is marked as authored by you (see image below). Let me know if you'd like me to change this so that it's not visible.

Bildschirm­foto 2023-06-12 um 11 34 43

**Comment by brandstetterm** [comment]
I think it would be cool if the border is actually transparent

**Comment by Schwehn42** [comment]
@brandstetterm I managed to change the avatar border to the accent color.  
For this, I had to modify the Avatar component to use a copy of the accent color mixin because the css color variables passed from the note component is overwritten by the parent component UserAvatar.

**Comment by brandstetterm** [comment]
Thank you for your work @Schwehn42 I'm going to have a look on it tomorrow 👍🏼

**Comment by brandstetterm** [comment]
Dear @Schwehn42,

would it be ok for you if we revert your changes from trying to change the border color? I agree with you and also think that it's too laborous and it somehow makes the code more complex IMO. Maybe you can go back to the [0f7873d](https://github.com/inovex/scrumlr.io/pull/3053/commits/0f7873d55139bef3d7417b4aacfe7930f6e212e2) Commit where just the avatar oder has been changed without messing with the border colors? 

Sorry for the inconvenience

**Review by brandstetterm — APPROVED** [review]
Thank you 😊

**Pull request merged**
