### PR TITLE
refactor: partially use revised icons

### PR DESCRIPTION
**Pull request by blxckOxymoron**
## Description

- #3268
The icons with the updated design from Figma need to be imported and updated in code.

## Changelog

- created a script to generate a `index.ts` file that exports all icons as named react components
- edit the svg by renaming the white `color` to `currentColor` and adding a class of `icon`
- added default styling for icons
- checked & updated styling (see all `.scss` files changed)
- updated the snapshots

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] The light- and dark-theme are both supported and tested
- [x] The design was implemented and is responsive for all devices and screen sizes
- [x] The application was tested in the most commonly used browsers (e.g. Chrome, Firefox, Safari)

## (Optional) Visual Changes

<details>
<summary><h1>full table of icon changes</h1></summary>
</img>
</img>
</details>

### CODE REVIEW

**Comment by brandstetterm** [comment]
Hey @blxckOxymoron, thank you for your huge contribution! Your changes look great and really helpful. Is it still work in progress or can it already be reviewed?

**Comment by blxckOxymoron** [comment]
Thank you for taking a look,
It's not 100% finished yet, since I need to check some more components for any style issues caused by the change.
I also found that some icons haven't been updated yet, as listed in the issue. When these are updated soon, they could be included in this PR as well.

Furthermore I'm unfortunately unable to work on this untill 05.04., but I will finish it when I'm back.

**Comment by blxckOxymoron** [comment]
I have finished looking through the places where things have changed.
There is now also a table attached, which lists all icons and how I tried to replace them.

**Comment by brandstetterm** [comment]
Thank you very much for your contribution @blxckOxymoron! Sorry that it took a while for your pull request to be merged

**Pull request merged**
