### PR TITLE
feat: add support for generic OpenID Connect authentication provider

### PR DESCRIPTION
**Pull request by UiP9AV6Y**
## Description

implementation for another authentication provider;
a generic OIDC IDP (ory, dex, authelia, keycloak, zitadel, gitlab, gitea, ...)

this feature was tested and developed against dex-idp but should be generic/configurable enough, to work against any arbitrary identity provider.

the requested scopes can be configured, while the read claims are still hardcoded.

## Changelog

* frontend: add login flow support for OpenID Connect
* backend: add support for generic OIDC authentication

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] The light- and dark-theme are both supported and tested
- [ ] The design was implemented and is responsive for all devices and screen sizes
- [ ] The application was tested in the most commonly used browsers (e.g. Chrome, Firefox, Safari)

### CODE REVIEW

**Comment by UiP9AV6Y** [comment]
the icons seem to originate from Figma and are exported/converted manually. as i have not access to the sources, i have edited an SVG i found on the internet. you might want to create an original one in Figma; same as for the Google and Microsoft icons

**Comment by Schwehn42** [comment]
cool idea, skimming over it looks pretty good! i'll try to add a proper review in the coming days.

**Comment by Schwehn42** [comment]
@mateo-ivc if you have time, could you take a look at this?

**Review by mateo-ivc — APPROVED** [review]
Looks so far good to me.
Nice work :)

**Pull request merged**
