### PR TITLE
improvement: Board Reaction Bar should remain open when you go to the stack view

### LINKED ISSUE #4083: Board Reaction Bar should remain open when you go to the stack view

### PR DESCRIPTION
**Pull request by Schwehn42**
## Description

The Board Reaction Bar will now remain open, assuming it already way, except when going to settings.  
Closes #4083.
## Changelog

- `MenuBars`
  - refactor `handleClickOutside`
  - clicking outside won't close the board reaction menu
  - effect handler for current location: going to "Settings" will close the board reaction menu.
- `BoardReactionMenu`
  - fixed z-index
  - fixed hover color
  - fixed cursor type
## Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] The application was tested in the most commonly used browsers (e.g. Chrome, Firefox, Safari)

### CODE REVIEW

**Review by brandstetterm — COMMENTED** [review]
I would suggest that we generally do not close the reaction bar when the user clicks outside the bar since (in my opinion) it's something that I want to have permanently open unless I close it manually.

**Comment by Schwehn42** [comment]
> I would suggest that we generally do not close the reaction bar when the user clicks outside the bar since (in my opinion) it's something that I want to have permanently open unless I close it manually.

generally agreed, what about going to the settings page? I'd close it there. @brandstetterm

**Comment by brandstetterm** [comment]
> generally agreed, what about going to the settings page? I'd close it there. @brandstetterm
I agree with you @Schwehn42

**Comment by Schwehn42** [comment]
@brandstetterm done ✅

**Review by brandstetterm — APPROVED** [review]

**Comment by brandstetterm** [comment]
Hey @Schwehn42,

I've checked our branch out to test the changes. At least on my machine, there was some weird behavior: 
- When the reaction bar is open and I click on a random position within the board, it closes
- When the reaction bar is open and I open the settings dialog, the bar is still open and closes only after clicking somewhere
- The reaction bar closes when I focus the note input
- The reaction bar closes when I start a timer
- The reaction bar closes when I start a voting

I think my suggestion has been that the bar stays open permanently until you manually press a button to close it again (with the exception of going to the settings dialog, then it should close automatically)

**Comment by Schwehn42** [comment]
@brandstetterm it works for me, I think you might have forgotten to pull the latest changes? 👀

**Comment by brandstetterm** [comment]
> @brandstetterm it works for me, I think you might have forgotten to pull the latest changes? 👀

Nevermind, my bad :D

**Review by brandstetterm — APPROVED** [review]

**Pull request merged**
