### PR TITLE
fix: Resolve tab navigation issue in Firefox

### PR DESCRIPTION
**Pull request by Aejkatappaja**
## Description

- Solving [#4500](https://github.com/inovex/scrumlr.io/issues/4500)
-  Improved focus management in the MiniMenu  and ColorPicker components by adding a focus lock by default. This ensures that users have a smoother interaction with the menu on every web browser.

## Changelog

- Enhancement: 
  - Apply focus locking by default on all browsers.
  - Changes applied on `MiniMenu` and `ColorPicker`

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] The light- and dark-theme are both supported and tested
- [x] The design was implemented and is responsive for all devices and screen sizes
- [x] The application was tested in the most commonly used browsers (e.g. Chrome, Firefox, Safari)

### CODE REVIEW

**Comment by Aejkatappaja** [comment]
> While the issue only applies to Firefox, it would be nice to have a general solution for this. Do you think that's possible?

Sure !

**Review by Schwehn42 — COMMENTED** [review]
lgtm, please do the same for `ColorPicker` as well, so you select the Color by pressing enter and tab within the ColorPicker :)

**Comment by Aejkatappaja** [comment]
> 4736a06

[4736a06](https://github.com/inovex/scrumlr.io/pull/4562/commits/4736a065fc9e18cfc2d2816c362b1a58e0c4cd2a)

**Review by Schwehn42 — APPROVED** [review]
lgtm, thanks for your contribution @Aejkatappaja 🫶

**Pull request merged**
