### PR TITLE
Update Hotkey keys

### LINKED ISSUE #2242: Change CMD+A hotkey
CMD+A is usually used to select the whole text, but it's now mapped to change the setting of show all authors. We should change that and update the hotkey PDF

### LINKED ISSUE #2243: Change CMD+1/2/3 hotkey
CMD+1/2/3 is used to switch between different tabs in most browsers and we should change the hotkey

### PR DESCRIPTION
**Pull request by NNKKOO**
- select note input is now mapped to "shift + < index >"
- show authors is now mapped to "shift + a"

this should close #2242  and also close #2243

### CODE REVIEW

**Comment by NNKKOO** [comment]
We still have to update the PDF

**Review by CronJorian — APPROVED** [review]
This will suffice, but personally I'd prefer to use option/alt over shift as a hotkey.
For the PDF to update, you should talk to @timengel, he made it as far as I know.

**Comment by timengel** [comment]
> This will suffice, but personally I'd prefer to use option/alt over shift as a hotkey.
> 
> For the PDF to update, you should talk to @timengel, he made it as far as I know.

@Kraft16 designed the Cheat Sheet 🙂

**Comment by NNKKOO** [comment]
Based on @CronJorian s suggestion, I changed the Hotkeys from shift to alt/option.
- _Select Note Input of Column_  ->  `alt/option`
- _Toggle „Show authors of notes“_  ->  `alt/option + A`

**Comment by NNKKOO** [comment]
I will wait with the merging until the pdf is adjusted accordingly

**Comment by Kraft-16** [comment]
@NNKKOO here is an updated cheat sheet in PDF format:
[New Cheat Sheet.pdf](https://github.com/inovex/scrumlr.io/files/9970214/New.Cheat.Sheet.pdf)

**Comment by NNKKOO** [comment]
> @NNKKOO here is an updated cheat sheet in PDF format: [New Cheat Sheet.pdf](https://github.com/inovex/scrumlr.io/files/9970214/New.Cheat.Sheet.pdf)

@Kraft-16  this cheat sheet is missing the 'alt'-key as an alternative for the 'option'-key. Would be nice if you could add it.

**Pull request merged**
