### PR TITLE
Remove tabIndex with a better document structure

### LINKED ISSUE #1713: Replace use of tabindex with better document structure
As a developer I want to get rid of the usage of `tabindex` and instead replace it by a better structure of the document, which will lead to the current tab order.

The usage of `tabindex` might be misleading for users and also it tends to break once we start changing up elements.

### PR DESCRIPTION
**Pull request by CronJorian**
## Description

[//]: <> (Explain the changes you’ve made. It doesn’t need to be fancy and you don’t have to get too technical.)

Closes #1713 

Removed tabIndex from the project. To retain focusability, non-interactive elements got mostly replaced by buttons, some by other interactive elements.
Additionally some missing focus and other css styles were added.

## Changelog

[//]: <> (Please provide a detailed list of the changes you have made to the codebase.)

Use this list to see detailed information about the respective file/component. As stated above it is mostly removing tabIndex, refactoring the structure and adjusting css to the structure or adding focus styles. 

- BoardHeader
  - refactor css
  - remove tabIndex
- Participant in ParticipantList
  - remove tabIndex
  - highlight on focus
- BoardUsers
  - fix structure
- Column
  - refactor and remove dead css
  - remove tabIndex
  - change structure to focus noteInput first and columnSettings afterwards
  - adjust test to structure
- ColumnSettings
  - remove tabIndex
- DotButton
  - remove tabIndex
- Dropdown/*
  - removed due to not being used and having a overly complex structure
- MenuBars
  - remove tabIndex
- Note
  - use button instead of div
  - remove tabIndex
  - add some missing css
  - adjust test
- NoteDialogNoteContent
  - adjust css
  - replace blockquote by textarea
- NoteInput
  - refactor css
  - add outline on focus
  - add tabIndex for addButton to skip focus on tab; remove remaining tabIndex
- Appearance
  - move code for themeSettings into own file
  - add useTranslation hook to update language automatically
- LanguageSettingsDropdown
  - replace static language selection with dynamic selection and new dropdown component
- SettingsDropdown
  - (hopefully) a generic dropdown component visually identical to the old languageSettingsDropdown
- ThemeSettings
  - moved from appearance component to own file
  - removed tabIndex
  - add css on focus
- ToggleButton
  - remove tabIndex
  - replace disabled attribute by aria-disabled to allow focus while disabled
  - adjust test
- TooltipButton
  - show tooltip on focus
  - change css to improve visibility
  - remove tabIndex
- AddButton / RemoveButton
  - remove tabIndex
- Votes
  - remove tabIndex
- style
  - change icon--medium size from 22px to 20px due to most use icons have a size 20px
- tabIndex
  - removed
- Board
  - remove tabIndex 

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] The light- and dark-theme are both supported and tested
- [x] The design was implemented and is responsive for all devices and screen sizes
- [x] The application was tested in the most commonly used browsers (e.g. Chrome, Firefox, Safari)
  - Note: Safari doesn't support border-radius on outlines with solid style, which is required for a custom color
  - Note: Neither does Safari support focus onClick which will then trigger a onBlur event

## (Optional) Visual Changes

[//]: <> (If available, please provide a before and after screenshot of your UI related changes.)
#### board

https://user-images.githubusercontent.com/44020029/189072629-3d962837-51a2-420d-b544-9fcdd5d08a37.mov

#### noteDialog

https://user-images.githubusercontent.com/44020029/189072900-c2ca11fb-731e-4d35-b6f7-2937cc8d878e.mov

#### appearance

https://user-images.githubusercontent.com/44020029/189074120-fd6eec8b-083a-4b05-927e-2694dbdeb063.mov

#### board

https://user-images.githubusercontent.com/44020029/189072319-f43ab0e2-735d-4aeb-b5ad-3ad83c310e05.mov

#### noteDialog

https://user-images.githubusercontent.com/44020029/189072762-1dba93af-4ffb-4e32-bb40-750adb387d41.mov

#### appearance

https://user-images.githubusercontent.com/44020029/189074279-94060cfd-6903-472d-961e-712393d8702e.mov

### CODE REVIEW

**Comment by Dominik-Weinzierl** [comment]
Looks good and works smooth - one minor nitpick: The close button of the side menus as a wrong focus style, or?
image

**Comment by Dominik-Weinzierl** [comment]
image

**Comment by CronJorian** [comment]
> image

This is due to firefox making the scrollbar accessible. When pressing space, the page is scrolling (shift+space is in reverse direction). I'll look into what's best practice about this, but will for sure change the outline.

**Comment by CronJorian** [comment]
> And last but not least which is probably not directly related to your changes, but if you have time you can check this too:
> 
>  Screen.Recording.2022-09-08.at.13.41.45.mov

Oh wowsie, this is great 😍 :P

**Comment by CronJorian** [comment]
@Dominik-Weinzierl the issue is linked to the confirmationDialog not having a <Portal> wrapper. Afterwards the focusLock works. Alternatively the focusLock can also be used inside the confirmationDialog component. I like the first one more because it solves problems with the confirmation of the board deletion inside the boardSettings.

Other than that, every noted issue is resolved.

**Comment by Dominik-Weinzierl** [comment]
mhm, i was still able to tab out of the leave board screen 🤔 

In addition, i noticed another minor nitpick :) 
image

**Review by Dominik-Weinzierl — APPROVED** [review]

**Pull request merged**
